
```{r}
  library(dplyr)
  library(lubridate)
```

```{r}
  source("R/ast_header.R")
  source("R/ast_log.R")
  source("R/upasv2x.R")
  source("R/upasv2.R")
  source("R/hhb.R")
  source("R/utils.R")
```

```{r}
  # file <- "inst/extdata/PS0166_LOG_2021-09-29T17_37_09UTC_test_______________---.txt"
  file <- "inst/extdata/PS1771_LOG_2024-06-13T21_20_17UTC_GPSoutside_________Eng.txt"
  # file <- "inst/extdata/PS1771_LOG_2024-06-13T21_31_26UTC_DIAGNOSTIC____________.txt"
  # file <- "inst/extdata/PS1771_LOG_2024-06-18T02_46_00UTC_NoGPS______________Eng.txt"
  # file <- "inst/extdata/PS1786_LOG_2023-03-02T21_45_43UTC_DIAGNOSTIC____________.txt"
  # file <- "inst/extdata/PSP00024_LOG_2021-08-11T18_18_03UTC_test____________test______.txt"
  # file <- "inst/extdata/PSP00030_LOG_2022-05-11T23_24_01UTC_---------------_----------.txt"
  # file <- "inst/extdata/PSP00055_LOG_2022-02-24T19_26_03UTC_test1___________----------.txt"
  # file <- "inst/extdata/PSP00055_LOG_2022-03-24T18_05_32UTC_DIAGNOSTIC________________.txt"
  # file <- "inst/extdata/PSP00270_LOG_2024-06-10T21_50_55UTC_name____________eng_______.txt"
  # file <- "inst/extdata/PSP00270_LOG_2024-06-13T16_24_47UTC_DIAGNOSTIC________________.txt"
  # file <- "inst/extdata/PSP00270_LOG_2024-06-14T18_36_07UTC_GPSin-out-in____eng_______.txt"
  # file <- "inst/extdata/PSP00270_LOG_2024-06-14T18_54_44UTC_NoGPS___________----------.txt"
  # file <- "inst/extdata/SH00007_LOG_2021-12-13T13_28_41UTC_---------------_-----.txt"
  # file <- "inst/extdata/SH00009_LOG_2022-02-14T17_02_32UTC_---------------_5VX__.txt"
  # file <- "tests/testthat/logfiles/MB00004_LOG_2023-12-12T16_43UTC.csv"
  # file <- "tests/testthat/logfiles/PSP00004_LOG_2022-08-29T03_36_18UTC_---------------_----------.txt"
  # file <- "tests/testthat/logfiles/PSP00020_LOG_2022-08-28T20_22_10UTC_---------------_----------.txt"
  # file <- "tests/testthat/logfiles/PSP00066_LOG_2022-09-02T18_03_56UTC_bike_test_1s____----------.txt"
```

```{r}
 log_raw <- fread_ast_log(file)
```

