#'Rename UPAS log file data frame columns
#'to be more user friendly for the Shiny app
#'
#' @param df Pass a upasv2x dataframe from read_ast_header function.
#'
#' @return A modified data frame with units added to column names of log data.
#' @export
#' @importFrom rlang .data
#'
#' @examples
#' upasv2x_log_units <- units_upasv2x_log(upasv2x_log)

shiny_log = function(df, df_h) {
  # units <- c("(HH:MM:SS)","(s)","(s)","(YYYY-MM-DDTHH:MM:SS)","(YYYY-MM-DDTHH:MM:SS)", "",
  #            "(L/min^-1)","(L*min^-1)","(L)",
  #            "(Pa)","(%)","(C)","(hPa)","(%RH)",
  #            "(g*L^-1)","(m ASL)","(-)","(decimalDegree)","(decimalDegree)",
  #            "(m)","(integer)","(m*s^-1)","(-)",
  #            "(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)","(mg)",
  #            "(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)",
  #            "(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)","(mdeg*s^-1)",
  #            "(%)","(%)","(%)","(%)","(%)","(%)","(#)","(lux)","(-)","(-)","(-)","(-)","(-)","(#)",
  #            "(ug*m^-3)","(ug*m^-3)","(ug*m^-3)","(ug*m^-3)","(ug*m^-3)","(ug*m^-3)","(ug*m^-3)","(ug*m^-3)",
  #            "(#*cm^-3)","(#*cm^-3)","(#*cm^-3)","(#*cm^-3)","(#*cm^-3)","(#*cm^-3)","(#*cm^-3)","(#*cm^-3)",
  #            "(#*cm^-3)","(#*cm^-3)",
  #            "(um)","(um)","(ug)","(C)","(C)","(C)","(C)","(ohm)","(hPa)",
  #            "(integer)","(integer)","(V)","(g*min^-1)","(V)","(integer)","(V)","(V)","(V)",
  #            "(bool)","(bool)","(bool)","(bool)","(bool)",
  #            "(s)","(s)","(s)","(s)","(s)","(s)","(ppm)","(C)","(%)","(-)","(-)")
  #colnames(df) <- paste(colnames(df), units, sep="")

  df <- df %>%
    dplyr::rename(`SampleTime(HH:MM:SS)` = .data$SampleTime,
                  `UnixTime(s)` = .data$UnixTime,
                  `UnixTimeMCU(s)` = .data$UnixTimeMCU,
                  `DateTimeUTC(YYYY-MM-DDTHH:MM:SS)` = .data$DateTimeUTC,
                  `DateTimeLocal(YYYY-MM-DDTHH:MM:SS)` = .data$DateTimeLocal,
                  `TZOffset(hrs)` = .data$TZOffset,
                  `PumpingFlowRate(LPM)` = .data$PumpingFlowRate,
                  `OverallFlowRate(LPM)` = .data$OverallFlowRate,
                  `SampledVolume(L)` = .data$SampledVolume,
                  `FilterDP(Pa)` = .data$FilterDP,
                  `BatteryCharge(%)` = .data$BatteryCharge,
                  `AtmoT(C)` = .data$AtmoT,
                  `AtmoP(hPa)` = .data$AtmoP,
                  `AtmoRH(%RH)` = .data$AtmoRH,
                  `AtmoDensity(g/L)` = .data$AtmoDensity,
                  `GPSQual` = .data$GPSQual,
                  `GPSlat(decimalDegrees)` = .data$GPSlat,
                  `GPSlon(decimalDegrees)` = .data$GPSlon,
                  `GPSalt(m)` = .data$GPSalt,
                  `GPSsat(integer)`= .data$GPSsat,
                  `GPSspeed(m/s)` = .data$GPSspeed,
                  `GPShDOP` = .data$GPShDOP,)

  if(df_h$ASTSampler=='UPAS_v2_x'){
    df <- df %>%
    dplyr::rename(`AtmoAlt(m ASL)` = .data$AtmoAlt,
                  `AccelX(mg)` = .data$AccelX,
                  `AccelXVar(mg)` = .data$AccelXVar,
                  `AccelXMin(mg)` = .data$AccelXMin,
                  `AccelXMax(mg)` = .data$AccelXMax,
                  `AccelY(mg)` = .data$AccelY,
                  `AccelYVar(mg)` = .data$AccelYVar,
                  `AccelYMin(mg)` = .data$AccelYMin,
                  `AccelYMax(mg)` = .data$AccelYMax,
                  `AccelZ(mg)` = .data$AccelZ,
                  `AccelZVar(mg)` = .data$AccelZVar,
                  `AccelZMin(mg)` = .data$AccelZMin,
                  `AccelZMax(mg)` = .data$AccelZMax,
                  `RotX(mdeg/s)` = .data$RotX,
                  `RotXVar(mdeg/s)` = .data$RotXVar,
                  `RotXMin(mdeg/s)` = .data$RotXMin,
                  `RotXMax(mdeg/s)` = .data$RotXMax,
                  `RotY(mdeg/s)` = .data$RotY,
                  `RotYVar(mdeg/s)` = .data$RotYVar,
                  `RotYMin(mdeg/s)` = .data$RotYMin,
                  `RotYMax(mdeg/s)` = .data$RotYMax,
                  `RotZ(mdeg/s)` = .data$RotZ,
                  `RotZVar(mdeg/s)` = .data$RotZVar,
                  `RotZMin(mdeg/s)` = .data$RotZMin,
                  `RotZMax(mdeg/s)` = .data$RotZMax,
                  `Xup(%)` = .data$Xup,
                  `XDown(%)` = .data$XDown,
                  `Yup(%)` = .data$Yup,
                  `Ydown(%)` = .data$Ydown,
                  `Zup(%)` = .data$Zup,
                  `Zdown(%)` = .data$Zdown,
                  `StepCount(#)` = .data$StepCount,
                  `LUX(lux)` = .data$LUX,
                  `UVindex` = .data$UVindex,
                  `HighVisRaw` = .data$HighVisRaw,
                  `LowVisRaw` = .data$LowVisRaw,
                  `IRRaw` = .data$IRRaw,
                  `UVRaw` = .data$UVRaw,
                  `PMMeasCnt(#)` = .data$PMMeasCnt,
                  `PM1MC(ug/m^3)` = .data$PM1MC,
                  `PM1MCVar(ug/m^3)` = .data$PM1MCVar,
                  `PM2_5MC(ug/m^3)` = .data$PM2_5MC,
                  `PM2_5MCVar(ug/m^3)` = .data$PM2_5MCVar,
                  `PM4MC(ug/m^3)` = .data$PM4MC,
                  `PM4MCVar(ug/m^3)` = .data$PM4MCVar,
                  `PM10MC(ug/m^3)` = .data$PM10MC,
                  `PM10MCVar(ug/m^3)` = .data$PM10MCVar,
                  `PM0_5NC(#/cm^3)` = .data$PM0_5NC,
                  `PM0_5NCVar(#/cm^3)` = .data$PM0_5NCVar,
                  `PM1NC(#/cm^3)` = .data$PM1NC,
                  `PM1NCVar(#/cm^3)` = .data$PM1NCVar,
                  `PM2_5NC(#/cm^3)` = .data$PM2_5NC,
                  `PM2_5NCVar(#/cm^3)` = .data$PM2_5NCVar,
                  `PM4NC(#/cm^3)` = .data$PM4NC,
                  `PM4NCVar(#/cm^3)` = .data$PM4NCVar,
                  `PM10NC(#/cm^3)` = .data$PM10NC,
                  `PM10NCVar(#/cm^3)` = .data$PM10NCVar,
                  `PMtypicalParticleSize(um)` = .data$PMtypicalParticleSize,
                  `PMtypicalParticleSizeVar(um)` = .data$PMtypicalParticleSizeVar,
                  `PM2_5SampledMass(ug)` = .data$PM2_5SampledMass,
                  `PCB1T(C)` = .data$PCB1T,
                  `PCB2T(C)` = .data$PCB2T,
                  `FdpT(C)` = .data$FdpT,
                  `AccelT(C)` = .data$AccelT,
                  `PT100R(ohm)` = .data$PT100R,
                  `PCB2P(hPa)` = .data$PCB2P,
                  `PumpPow1(integer)` = .data$PumpPow1,
                  `PumpPow2(integer)` = .data$PumpPow2,
                  `PumpV(V)` = .data$PumpV,
                  `MassFlow(g/min)` = .data$MassFlow,
                  `MFSVout(V)` = .data$MFSVout,
                  `BFGenergy(16-bit integer)` = .data$BFGenergy,
                  `BattVolt(V)` = .data$BattVolt,
                  `v3_3(V)` = .data$v3_3,
                  `v5(V)` = .data$v5,
                  `PumpsON(bool)` = .data$PumpsON,
                  `Dead(bool)` = .data$Dead,
                  `BCS1(bool)` = .data$BCS1,
                  `BCS2(bool)` = .data$BCS2,
                  `BC_NPG(bool)` = .data$BC_NPG,
                  `FLOWCTL(s)` = .data$FLOWCTL,
                  `GPSRT(s)` = .data$GPSRT,
                  `SD_DATAW(s)` = .data$SD_DATAW,
                  `SD_HEADW(s)` = .data$SD_HEADW,
                  `TPumpsOFF(s)` = .data$TPumpsOFF,
                  `TPumpsON(s)` = .data$TPumpsON,
                  # `IAQStabStat` = .data$IAQStabStat,
                  # `IAQRunIn` = .data$IAQRunIn,
                  # `IAQRes(ohms)` = .data$IAQRes,
                  # `IAQ` = .data$IAQ,
                  # `IAQAcc` = .data$IAQAcc,
                  # `StaticIAQ` = .data$StaticIAQ,
                  # `StaticIAQAcc` = .data$StaticIAQAcc,
                  # `CO2e(ppm)` = .data$CO2e,
                  # `CO2eAcc` = .data$CO2eAcc,
                  # `bVOC(ppm)` = .data$bVOC,
                  # `bVOCAcc` = .data$bVOCAcc,
                  # `gasComp` = .data$gasComp,
                  # `gasCompAcc` = .data$gasCompAcc,
                  # `gasPerc(%)` = .data$gasPerc,
                  # `gasPercAcc` = .data$gasPercAcc,
                  # `tz_value` = .data$tz_value,
                  #`ASTSampler` = .data$ASTSampler,
                  # `UPASserial` = .data$UPASserial,
                  # `SampleName` = .data$SampleName,
                  # `CartridgeID` = .data$CartridgeID,
                  `StartDateTimeUTC(YYYY-MM-DDTHH:MM:SS)` = .data$StartDateTimeUTC
                  # `LogFileMode` = .data$LogFileMode
    )
  }

  return(df)
}
